import Foundation

enum TRAILER_DEFECTS: String, CaseIterable {
    case BRAKE_CONNECTIONS = "Brake Connections"
    case BRAKES = "Brakes"
    case COUPLING_DEVICES = "Coupling Devices"
    case COUPLING_PIN = "Coupling Pin"
    case DOORS = "Doors"
    case HITCH = "Hitch"
    case LANDING_GEAR = "Landing Gear"
    case LIGHTS = "Lights"
    case OTHER = "Other"
    case REFLECTORS = "Reflectors"
    case ROOF = "Roof"
    case STRAPS = "Straps"
    case SUSPENSION_SYSTEM = "Suspension System"
    case TARPAULIN = "Tarpaulin"
    case TIRES = "Tires"
    case WHEELS_AND_RIMS = "Wheels & Rims"
}

enum VEHICLE_DEFECTS: String, CaseIterable {
    case AIR_COMPRESSOR = "Air Compressor"
    case AIR_LINES = "Air Lines"
    case BATTERY = "Battery"
    case BELTS_AND_HOSES = "Belts & Hoses"
    case BODY = "Body"
    case BRAKE_ACCESSORIES = "Brake Accessories"
    case CLUTCH = "Clutch"
    case COUPLING_DEVICES = "Coupling Devices"
    case DEFROSTER = "Defroster"
    case DRIVE_LINE = "Drive Line"
    case ENGINE = "Engine"
    case EXHAUST = "Exhaust"
    case FIFTH_WHEEL = "Fifth Wheel"
    case FLUID_LEVELS = "Fluid Levels"
    case FRAME_AND_ASSEMBLY = "Frame & Assembly"
    case FRONT_AXLE = "Front Axle"
    case FUEL_TANKS = "Fuel Tanks"
    case HEADLIGHTS = "Headlights"
    case HEATER = "Heater"
    case HORN = "Horn"
    case MIRRORS = "Mirrors"
    case MUFFLER = "Muffler"
    case OIL_LEVEL = "Oil Level"
    case PARKING_BRAKES = "Parking Brakes"
    case RADIATOR_LEVEL = "Radiator Level"
    case REFLECTORS = "Reflectors"
    case SAFETY_EQUIPMENT = "Safety Equipment"
    case SERVICE_BRAKES = "Service Brakes"
    case SERVICE_DOOR = "Service Door"
    case STARTER = "Starter"
    case STEERING = "Steering"
    case SUSPENSION_SYSTEM = "Suspension System"
    case TAIL_LIGHTS = "Tail Lights"
    case TIRE_CHAINS = "Tire Chains"
    case TIRES = "Tires"
    case TRANSMISSION = "Transmission"
    case TRIP_RECORDER = "Trip Recorder"
    case TURN_INDICATORS = "Turn Indicators"
    case WHEEL_AND_RIMS = "Wheel & Rims"
    case WINDOWS = "Windows"
    case WINDSHIELD = "Windshield"
    case WIPERS_AND_WASHERS = "Wipers & Washers"
}
